rvm:
- 2.6

script: ./script/cibuild

before_script:
- chmod +x ./script/cibuild

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  repo: chenuin/chenuin.github.io
  local_dir: ./_site
  target_branch: master
  on:
    branch: master
